project_id = "ypkiikefrcpkqmwacjjb"

[functions.analisar-storage]
verify_jwt = true

[functions.limpar-storage]
verify_jwt = true

[functions.limpar-tudo]
verify_jwt = true

[functions.deletar-processo]
verify_jwt = true

[functions.deletar-usuario-admin]
verify_jwt = true

[functions.criar-usuario-admin]
verify_jwt = true

[functions.resetar-senha-usuario]
verify_jwt = true

[functions.enviar-email-recuperacao]
verify_jwt = false

[functions.verificar-encaminhamento]
verify_jwt = false
